[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nalpy"
authors = [
    { name = "Niko Leinonen" }
]
requires-python = ">=3.11"
description = "An experimental portable package for different types of projects."
version = "0.1.4"
